name: Deploy to SFTP Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Remove unwanted folders before deploy
        run: |
          rm -rf .git .github node_modules *.log

      - name: SFTP Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: access-5016253559.webspace-host.com
          username: a549875
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: ./
          remote_path: wordpress/wp-content/plugins/octo-print-designer
          port: 22
          delete_remote_files: true
